name: life_admin
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  side_navigation: ^1.0.4
  syncfusion_flutter_charts: ^25.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.6

flutter:
  uses-material-design: true
